language: node_js
sudo: required
addons:
 chrome: stable
node_js:
  - 12
install:
  - npm install
  - npm install -g codeclimate-test-reporter
script:
  - npm run eslint
  - npm run coverage
  - codeclimate-test-reporter < coverage/lcov.info
