language: node_js
node_js:
  - 8.10.0
install:
  - npm install
  - npm install -g codeclimate-test-reporter
script:
  - npm run eslint
  - npm run coverage
  - codeclimate-test-reporter < coverage/lcov.info
